[phases.setup]
nixPkgs = ["python311", "nodejs_20", "nodePackages.npm"]

[phases.install]
cmds = [
  "pip install -r requirements.txt",
  "npm install --prefix frontend"
]

[phases.build]
cmds = [
  "npm run build --prefix frontend"
]

[start]
cmd = "python create_sqlite_db.py && uvicorn api_sqlite:app --host 0.0.0.0 --port $PORT"
